// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nxtpop/airdrop/v1beta1/allocation.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AirdropAllocation defines the user's airdrop allocation.
type AirdropAllocation struct {
	Chain         string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount        int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Claimed       bool   `protobuf:"varint,4,opt,name=claimed,proto3" json:"claimed,omitempty"`
	RewardAddress string `protobuf:"bytes,5,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
}

func (m *AirdropAllocation) Reset()         { *m = AirdropAllocation{} }
func (m *AirdropAllocation) String() string { return proto.CompactTextString(m) }
func (*AirdropAllocation) ProtoMessage()    {}
func (*AirdropAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f443a60d83adb6, []int{0}
}
func (m *AirdropAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AirdropAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AirdropAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AirdropAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AirdropAllocation.Merge(m, src)
}
func (m *AirdropAllocation) XXX_Size() int {
	return m.Size()
}
func (m *AirdropAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AirdropAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_AirdropAllocation proto.InternalMessageInfo

func (m *AirdropAllocation) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *AirdropAllocation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AirdropAllocation) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AirdropAllocation) GetClaimed() bool {
	if m != nil {
		return m.Claimed
	}
	return false
}

func (m *AirdropAllocation) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*AirdropAllocation)(nil), "nxtpop.airdrop.v1beta1.AirdropAllocation")
}

func init() {
	proto.RegisterFile("nxtpop/airdrop/v1beta1/allocation.proto", fileDescriptor_33f443a60d83adb6)
}

var fileDescriptor_33f443a60d83adb6 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4a, 0xec, 0x30,
	0x14, 0x86, 0x27, 0x77, 0xee, 0x8c, 0x1a, 0x50, 0xb0, 0x0c, 0x43, 0x99, 0x45, 0x28, 0x82, 0xd8,
	0x8d, 0x0d, 0x83, 0x1b, 0xb7, 0xd5, 0x07, 0x70, 0xa8, 0x3b, 0x37, 0x72, 0x9a, 0x86, 0x4e, 0xa0,
	0xed, 0x29, 0x49, 0x46, 0xc7, 0xb7, 0xf0, 0x01, 0x7c, 0x20, 0x97, 0xb3, 0x74, 0x29, 0xed, 0x8b,
	0xc8, 0x34, 0x6d, 0x77, 0xf9, 0x7f, 0xbe, 0x7c, 0xc9, 0x39, 0xf4, 0xa6, 0xda, 0xdb, 0x1a, 0x6b,
	0x0e, 0x4a, 0x67, 0x1a, 0x6b, 0xfe, 0xb6, 0x4e, 0xa5, 0x85, 0x35, 0x87, 0xa2, 0x40, 0x01, 0x56,
	0x61, 0x15, 0xd5, 0x1a, 0x2d, 0x7a, 0x4b, 0x07, 0x46, 0x3d, 0x18, 0xf5, 0xe0, 0x6a, 0x91, 0x63,
	0x8e, 0x1d, 0xc2, 0x8f, 0x27, 0x47, 0xaf, 0x98, 0x40, 0x53, 0xa2, 0xe1, 0x29, 0x18, 0x39, 0x3a,
	0x05, 0xaa, 0xde, 0x76, 0xf5, 0x45, 0xe8, 0x65, 0xec, 0x4c, 0xf1, 0xf8, 0x92, 0xb7, 0xa0, 0x33,
	0xb1, 0x05, 0x55, 0xf9, 0x24, 0x20, 0xe1, 0x59, 0xe2, 0x82, 0xe7, 0xd3, 0x13, 0xc8, 0x32, 0x2d,
	0x8d, 0xf1, 0xff, 0x75, 0xfd, 0x10, 0xbd, 0x25, 0x9d, 0x43, 0x89, 0xbb, 0xca, 0xfa, 0xd3, 0x80,
	0x84, 0xd3, 0xa4, 0x4f, 0xc7, 0x1b, 0xa2, 0x00, 0x55, 0xca, 0xcc, 0xff, 0x1f, 0x90, 0xf0, 0x34,
	0x19, 0xa2, 0x77, 0x4d, 0x2f, 0xb4, 0x7c, 0x07, 0x9d, 0xbd, 0x0e, 0xca, 0x59, 0xa7, 0x3c, 0x77,
	0x6d, 0xec, 0xca, 0x87, 0xe4, 0xbb, 0x61, 0xe4, 0xd0, 0x30, 0xf2, 0xdb, 0x30, 0xf2, 0xd9, 0xb2,
	0xc9, 0xa1, 0x65, 0x93, 0x9f, 0x96, 0x4d, 0x5e, 0xee, 0x73, 0x65, 0xb7, 0xbb, 0x34, 0x12, 0x58,
	0xf2, 0xcd, 0xd3, 0xe6, 0xb9, 0x04, 0x6d, 0x1f, 0xb1, 0xb2, 0x1a, 0x84, 0xe5, 0x6e, 0x45, 0xb7,
	0xdd, 0xb7, 0xf9, 0x7e, 0xdc, 0xa9, 0xfd, 0xa8, 0xa5, 0x49, 0xe7, 0xdd, 0xe4, 0x77, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x93, 0xf7, 0xdd, 0xb2, 0x72, 0x01, 0x00, 0x00,
}

func (m *AirdropAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AirdropAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AirdropAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintAllocation(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Claimed {
		i--
		if m.Claimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Amount != 0 {
		i = encodeVarintAllocation(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAllocation(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintAllocation(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAllocation(dAtA []byte, offset int, v uint64) int {
	offset -= sovAllocation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AirdropAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovAllocation(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAllocation(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovAllocation(uint64(m.Amount))
	}
	if m.Claimed {
		n += 2
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovAllocation(uint64(l))
	}
	return n
}

func sovAllocation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAllocation(x uint64) (n int) {
	return sovAllocation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AirdropAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAllocation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AirdropAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AirdropAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Claimed = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAllocation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAllocation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAllocation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAllocation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAllocation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllocation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAllocation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAllocation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAllocation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAllocation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAllocation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAllocation = fmt.Errorf("proto: unexpected end of group")
)
