// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nxtpop/airdrop/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgClaimAllocation defines an sdk.Msg type that claims airdrop allocation
type MsgClaimAllocation struct {
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RewardAddress string `protobuf:"bytes,2,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgClaimAllocation) Reset()         { *m = MsgClaimAllocation{} }
func (m *MsgClaimAllocation) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAllocation) ProtoMessage()    {}
func (*MsgClaimAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c1518cb39d49b0, []int{0}
}
func (m *MsgClaimAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAllocation.Merge(m, src)
}
func (m *MsgClaimAllocation) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAllocation proto.InternalMessageInfo

// MsgClaimAllocationResponse defines the Msg/ClaimAllocation response type.
type MsgClaimAllocationResponse struct {
}

func (m *MsgClaimAllocationResponse) Reset()         { *m = MsgClaimAllocationResponse{} }
func (m *MsgClaimAllocationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAllocationResponse) ProtoMessage()    {}
func (*MsgClaimAllocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c1518cb39d49b0, []int{1}
}
func (m *MsgClaimAllocationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAllocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAllocationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAllocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAllocationResponse.Merge(m, src)
}
func (m *MsgClaimAllocationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAllocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAllocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAllocationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClaimAllocation)(nil), "nxtpop.airdrop.v1beta1.MsgClaimAllocation")
	proto.RegisterType((*MsgClaimAllocationResponse)(nil), "nxtpop.airdrop.v1beta1.MsgClaimAllocationResponse")
}

func init() { proto.RegisterFile("nxtpop/airdrop/v1beta1/tx.proto", fileDescriptor_d9c1518cb39d49b0) }

var fileDescriptor_d9c1518cb39d49b0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd1, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0x07, 0xf0, 0x3b, 0x0b, 0x6a, 0x83, 0x3f, 0xe0, 0x10, 0xa9, 0x47, 0xb9, 0x96, 0x82, 0x50,
	0x04, 0x13, 0x5a, 0x17, 0x71, 0xab, 0x9d, 0x8b, 0xe5, 0xdc, 0x5c, 0x24, 0x77, 0x17, 0xd3, 0xc0,
	0x35, 0x2f, 0x26, 0xa9, 0x5e, 0x07, 0x77, 0x47, 0xff, 0x84, 0xfe, 0x39, 0x8e, 0x1d, 0x1d, 0xa5,
	0x5d, 0xfc, 0x33, 0xc4, 0xbb, 0x9e, 0x82, 0x75, 0x70, 0xcb, 0x7b, 0xf9, 0x90, 0x6f, 0x78, 0x0f,
	0x35, 0x64, 0x66, 0x15, 0x28, 0x42, 0x85, 0x4e, 0x34, 0x28, 0xf2, 0xd0, 0x89, 0x98, 0xa5, 0x1d,
	0x62, 0x33, 0xac, 0x34, 0x58, 0xf0, 0x0e, 0x0b, 0x80, 0x57, 0x00, 0xaf, 0x80, 0x7f, 0xc0, 0x81,
	0x43, 0x4e, 0xc8, 0xd7, 0xa9, 0xd0, 0xfe, 0x11, 0x07, 0xe0, 0x29, 0x23, 0x79, 0x15, 0x4d, 0xee,
	0x08, 0x95, 0xd3, 0xe2, 0xaa, 0xf5, 0x84, 0xbc, 0x81, 0xe1, 0xfd, 0x94, 0x8a, 0x71, 0x2f, 0x4d,
	0x21, 0xa6, 0x56, 0x80, 0xf4, 0x6a, 0x68, 0x8b, 0x26, 0x89, 0x66, 0xc6, 0xd4, 0xdc, 0xa6, 0xdb,
	0xae, 0x86, 0x65, 0xe9, 0x1d, 0xa3, 0x3d, 0xcd, 0x1e, 0xa9, 0x4e, 0x6e, 0x4b, 0xb0, 0x91, 0x83,
	0xdd, 0xa2, 0xdb, 0x5b, 0xb1, 0x3a, 0xaa, 0x1a, 0xc1, 0x25, 0xb5, 0x13, 0xcd, 0x6a, 0x95, 0xa6,
	0xdb, 0xde, 0x09, 0x7f, 0x1a, 0x17, 0xdb, 0xcf, 0xb3, 0x86, 0xf3, 0x31, 0x6b, 0x38, 0xad, 0x3a,
	0xf2, 0xd7, 0xe3, 0x43, 0x66, 0x14, 0x48, 0xc3, 0xba, 0x19, 0xaa, 0x0c, 0x0c, 0xf7, 0xee, 0xd1,
	0xfe, 0xef, 0x0f, 0x9e, 0xe0, 0xbf, 0x07, 0x80, 0xd7, 0x5f, 0xf3, 0xbb, 0xff, 0xb7, 0x65, 0xf2,
	0x65, 0xf8, 0xba, 0x08, 0xdc, 0xf9, 0x22, 0x70, 0xdf, 0x17, 0x81, 0xfb, 0xb2, 0x0c, 0x9c, 0xf9,
	0x32, 0x70, 0xde, 0x96, 0x81, 0x73, 0x73, 0xce, 0x85, 0x1d, 0x4d, 0x22, 0x1c, 0xc3, 0x98, 0x0c,
	0xaf, 0x86, 0xd7, 0x63, 0xaa, 0x6d, 0x1f, 0xa4, 0xd5, 0x34, 0xb6, 0xa4, 0x08, 0x3a, 0x8d, 0x47,
	0x54, 0x48, 0x92, 0x7d, 0xaf, 0xcf, 0x4e, 0x15, 0x33, 0xd1, 0x66, 0x3e, 0xf1, 0xb3, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x73, 0xbb, 0x1c, 0xdd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ClaimAllocation defines a method to create new proposal given a content.
	ClaimAllocation(ctx context.Context, in *MsgClaimAllocation, opts ...grpc.CallOption) (*MsgClaimAllocationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimAllocation(ctx context.Context, in *MsgClaimAllocation, opts ...grpc.CallOption) (*MsgClaimAllocationResponse, error) {
	out := new(MsgClaimAllocationResponse)
	err := c.cc.Invoke(ctx, "/nxtpop.airdrop.v1beta1.Msg/ClaimAllocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ClaimAllocation defines a method to create new proposal given a content.
	ClaimAllocation(context.Context, *MsgClaimAllocation) (*MsgClaimAllocationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimAllocation(ctx context.Context, req *MsgClaimAllocation) (*MsgClaimAllocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimAllocation not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimAllocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nxtpop.airdrop.v1beta1.Msg/ClaimAllocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimAllocation(ctx, req.(*MsgClaimAllocation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nxtpop.airdrop.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimAllocation",
			Handler:    _Msg_ClaimAllocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nxtpop/airdrop/v1beta1/tx.proto",
}

func (m *MsgClaimAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimAllocationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAllocationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAllocationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimAllocationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAllocationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAllocationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAllocationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
