// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: teritori/airdrop/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSetAllocation defines an sdk.Msg type that set airdrop allocation
type MsgSetAllocation struct {
	Sender     string            `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Allocation AirdropAllocation `protobuf:"bytes,2,opt,name=allocation,proto3" json:"allocation"`
}

func (m *MsgSetAllocation) Reset()         { *m = MsgSetAllocation{} }
func (m *MsgSetAllocation) String() string { return proto.CompactTextString(m) }
func (*MsgSetAllocation) ProtoMessage()    {}
func (*MsgSetAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{0}
}
func (m *MsgSetAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAllocation.Merge(m, src)
}
func (m *MsgSetAllocation) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAllocation proto.InternalMessageInfo

func (m *MsgSetAllocation) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSetAllocation) GetAllocation() AirdropAllocation {
	if m != nil {
		return m.Allocation
	}
	return AirdropAllocation{}
}

// MsgSetAllocationResponse defines the Msg/SetAllocation response type.
type MsgSetAllocationResponse struct {
}

func (m *MsgSetAllocationResponse) Reset()         { *m = MsgSetAllocationResponse{} }
func (m *MsgSetAllocationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetAllocationResponse) ProtoMessage()    {}
func (*MsgSetAllocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{1}
}
func (m *MsgSetAllocationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetAllocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetAllocationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetAllocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAllocationResponse.Merge(m, src)
}
func (m *MsgSetAllocationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetAllocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAllocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAllocationResponse proto.InternalMessageInfo

// MsgClaimAllocation defines an sdk.Msg type that claims airdrop allocation
type MsgClaimAllocation struct {
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey        string `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	RewardAddress string `protobuf:"bytes,3,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgClaimAllocation) Reset()         { *m = MsgClaimAllocation{} }
func (m *MsgClaimAllocation) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAllocation) ProtoMessage()    {}
func (*MsgClaimAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{2}
}
func (m *MsgClaimAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAllocation.Merge(m, src)
}
func (m *MsgClaimAllocation) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAllocation proto.InternalMessageInfo

// MsgClaimAllocationResponse defines the Msg/ClaimAllocation response type.
type MsgClaimAllocationResponse struct {
}

func (m *MsgClaimAllocationResponse) Reset()         { *m = MsgClaimAllocationResponse{} }
func (m *MsgClaimAllocationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimAllocationResponse) ProtoMessage()    {}
func (*MsgClaimAllocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{3}
}
func (m *MsgClaimAllocationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimAllocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimAllocationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimAllocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimAllocationResponse.Merge(m, src)
}
func (m *MsgClaimAllocationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimAllocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimAllocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimAllocationResponse proto.InternalMessageInfo

// MsgSignData defines an arbitrary, general-purpose, off-chain message
type MsgSignData struct {
	// Signer is the sdk.AccAddress of the message signer
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer"`
	// data represents the raw bytes of the content that is signed (text, json, etc)
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *MsgSignData) Reset()         { *m = MsgSignData{} }
func (m *MsgSignData) String() string { return proto.CompactTextString(m) }
func (*MsgSignData) ProtoMessage()    {}
func (*MsgSignData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{4}
}
func (m *MsgSignData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignData.Merge(m, src)
}
func (m *MsgSignData) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignData proto.InternalMessageInfo

func (m *MsgSignData) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgSignData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MsgTransferModuleOwnership struct {
	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	NewOwner string `protobuf:"bytes,2,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
}

func (m *MsgTransferModuleOwnership) Reset()         { *m = MsgTransferModuleOwnership{} }
func (m *MsgTransferModuleOwnership) String() string { return proto.CompactTextString(m) }
func (*MsgTransferModuleOwnership) ProtoMessage()    {}
func (*MsgTransferModuleOwnership) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{5}
}
func (m *MsgTransferModuleOwnership) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferModuleOwnership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferModuleOwnership.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferModuleOwnership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferModuleOwnership.Merge(m, src)
}
func (m *MsgTransferModuleOwnership) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferModuleOwnership) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferModuleOwnership.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferModuleOwnership proto.InternalMessageInfo

func (m *MsgTransferModuleOwnership) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgTransferModuleOwnership) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

type MsgTransferModuleOwnershipResponse struct {
}

func (m *MsgTransferModuleOwnershipResponse) Reset()         { *m = MsgTransferModuleOwnershipResponse{} }
func (m *MsgTransferModuleOwnershipResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferModuleOwnershipResponse) ProtoMessage()    {}
func (*MsgTransferModuleOwnershipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{6}
}
func (m *MsgTransferModuleOwnershipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferModuleOwnershipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferModuleOwnershipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferModuleOwnershipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferModuleOwnershipResponse.Merge(m, src)
}
func (m *MsgTransferModuleOwnershipResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferModuleOwnershipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferModuleOwnershipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferModuleOwnershipResponse proto.InternalMessageInfo

type MsgDepositTokens struct {
	Sender string                                    `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount []github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,2,rep,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount"`
}

func (m *MsgDepositTokens) Reset()         { *m = MsgDepositTokens{} }
func (m *MsgDepositTokens) String() string { return proto.CompactTextString(m) }
func (*MsgDepositTokens) ProtoMessage()    {}
func (*MsgDepositTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{7}
}
func (m *MsgDepositTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositTokens.Merge(m, src)
}
func (m *MsgDepositTokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositTokens proto.InternalMessageInfo

func (m *MsgDepositTokens) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgDepositTokensResponse struct {
}

func (m *MsgDepositTokensResponse) Reset()         { *m = MsgDepositTokensResponse{} }
func (m *MsgDepositTokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositTokensResponse) ProtoMessage()    {}
func (*MsgDepositTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbdab318d176f45, []int{8}
}
func (m *MsgDepositTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositTokensResponse.Merge(m, src)
}
func (m *MsgDepositTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositTokensResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetAllocation)(nil), "teritori.airdrop.v1beta1.MsgSetAllocation")
	proto.RegisterType((*MsgSetAllocationResponse)(nil), "teritori.airdrop.v1beta1.MsgSetAllocationResponse")
	proto.RegisterType((*MsgClaimAllocation)(nil), "teritori.airdrop.v1beta1.MsgClaimAllocation")
	proto.RegisterType((*MsgClaimAllocationResponse)(nil), "teritori.airdrop.v1beta1.MsgClaimAllocationResponse")
	proto.RegisterType((*MsgSignData)(nil), "teritori.airdrop.v1beta1.MsgSignData")
	proto.RegisterType((*MsgTransferModuleOwnership)(nil), "teritori.airdrop.v1beta1.MsgTransferModuleOwnership")
	proto.RegisterType((*MsgTransferModuleOwnershipResponse)(nil), "teritori.airdrop.v1beta1.MsgTransferModuleOwnershipResponse")
	proto.RegisterType((*MsgDepositTokens)(nil), "teritori.airdrop.v1beta1.MsgDepositTokens")
	proto.RegisterType((*MsgDepositTokensResponse)(nil), "teritori.airdrop.v1beta1.MsgDepositTokensResponse")
}

func init() { proto.RegisterFile("teritori/airdrop/v1beta1/tx.proto", fileDescriptor_2fbdab318d176f45) }

var fileDescriptor_2fbdab318d176f45 = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6f, 0xd3, 0x3e,
	0x18, 0x4e, 0xd6, 0xa9, 0x5b, 0xbd, 0xdf, 0x7e, 0xa0, 0x08, 0xb1, 0x10, 0xa6, 0x64, 0x44, 0x20,
	0xc6, 0xc7, 0x12, 0xad, 0x70, 0x42, 0x5c, 0xd6, 0x0d, 0xa1, 0x09, 0xaa, 0x69, 0xa1, 0x27, 0x2e,
	0x93, 0xd3, 0x78, 0xa9, 0xd5, 0xd6, 0x8e, 0x6c, 0x87, 0xae, 0x07, 0xee, 0x5c, 0x90, 0x38, 0x71,
	0xde, 0x9f, 0xb3, 0xe3, 0x8e, 0x88, 0x43, 0x85, 0xda, 0x0b, 0xda, 0x81, 0xbf, 0x01, 0xd5, 0x75,
	0xfa, 0xb1, 0x91, 0xf2, 0x71, 0xa9, 0xfb, 0xda, 0xcf, 0xfb, 0x3e, 0x8f, 0xdf, 0xf7, 0x89, 0xc1,
	0x1d, 0x81, 0x18, 0x16, 0x94, 0x61, 0x1f, 0x62, 0x16, 0x31, 0x9a, 0xf8, 0xef, 0xb6, 0x43, 0x24,
	0xe0, 0xb6, 0x2f, 0x4e, 0xbc, 0x84, 0x51, 0x41, 0x0d, 0x33, 0x83, 0x78, 0x0a, 0xe2, 0x29, 0x88,
	0x75, 0x23, 0xa6, 0x31, 0x95, 0x20, 0x7f, 0xf8, 0x6f, 0x84, 0xb7, 0x6e, 0xc5, 0x94, 0xc6, 0x2d,
	0xe4, 0xcb, 0x28, 0x4c, 0x8f, 0x7d, 0x48, 0xba, 0xea, 0xe8, 0x41, 0x2e, 0x1b, 0x6c, 0xb5, 0x68,
	0x1d, 0x0a, 0x4c, 0xc9, 0x08, 0xea, 0xbe, 0x07, 0xd7, 0xab, 0x3c, 0x7e, 0x83, 0xc4, 0xce, 0xf8,
	0xc4, 0xb8, 0x09, 0x8a, 0x1c, 0x91, 0x08, 0x31, 0x53, 0xdf, 0xd0, 0x37, 0x4b, 0x81, 0x8a, 0x8c,
	0x43, 0x00, 0x26, 0xf9, 0xe6, 0xc2, 0x86, 0xbe, 0xb9, 0x52, 0x7e, 0xe4, 0xe5, 0xc9, 0xf6, 0x76,
	0x46, 0xf1, 0xa4, 0x70, 0x65, 0xf1, 0xac, 0xe7, 0x68, 0xc1, 0x54, 0x11, 0xd7, 0x02, 0xe6, 0x65,
	0xfa, 0x00, 0xf1, 0x84, 0x12, 0x8e, 0xdc, 0xcf, 0x3a, 0x30, 0xaa, 0x3c, 0xde, 0x6d, 0x41, 0xdc,
	0x9e, 0x52, 0x67, 0x82, 0x25, 0x18, 0x45, 0x0c, 0x71, 0xae, 0xe4, 0x65, 0xa1, 0xb1, 0x06, 0x96,
	0x92, 0x34, 0x3c, 0x6a, 0xa2, 0xae, 0x14, 0x57, 0x0a, 0x8a, 0x49, 0x1a, 0xbe, 0x42, 0x5d, 0xe3,
	0x1e, 0xf8, 0x9f, 0xa1, 0x0e, 0x64, 0xd1, 0x51, 0x96, 0x59, 0x90, 0xe7, 0xab, 0xa3, 0xdd, 0x1d,
	0x95, 0xbf, 0x0e, 0x4a, 0x1c, 0xc7, 0x04, 0x8a, 0x94, 0x21, 0x73, 0x51, 0x22, 0x26, 0x1b, 0xcf,
	0x96, 0x3f, 0x9c, 0x3a, 0xda, 0xf7, 0x53, 0x47, 0x73, 0xd7, 0x81, 0x75, 0x55, 0xd7, 0x58, 0xf6,
	0x01, 0x58, 0x19, 0x5e, 0x09, 0xc7, 0x64, 0x0f, 0x0a, 0x68, 0xb8, 0xa0, 0x38, 0xac, 0x91, 0x35,
	0xb3, 0x02, 0x2e, 0x7a, 0x8e, 0xda, 0x09, 0xd4, 0x6a, 0xac, 0x83, 0xc5, 0x08, 0x0a, 0x28, 0x55,
	0xff, 0x57, 0x59, 0xbe, 0xe8, 0x39, 0x32, 0x0e, 0xe4, 0xaf, 0x7b, 0x28, 0xe9, 0x6a, 0x0c, 0x12,
	0x7e, 0x8c, 0x58, 0x95, 0x46, 0x69, 0x0b, 0x1d, 0x74, 0x08, 0x62, 0xbc, 0x81, 0x93, 0xdc, 0x61,
	0xdd, 0x06, 0x25, 0x82, 0x3a, 0x47, 0x74, 0x08, 0x54, 0xed, 0x58, 0x26, 0xa8, 0x23, 0x13, 0xdd,
	0xbb, 0xc0, 0xcd, 0x2f, 0x39, 0xbe, 0x09, 0x97, 0xde, 0xd8, 0x43, 0x09, 0xe5, 0x58, 0xd4, 0x68,
	0x13, 0x11, 0x9e, 0x4b, 0xf7, 0x12, 0x14, 0x61, 0x9b, 0xa6, 0x44, 0x98, 0x0b, 0x1b, 0x85, 0xcd,
	0x52, 0xc5, 0x1f, 0x8e, 0xfa, 0x6b, 0xcf, 0xb9, 0x1f, 0x63, 0xd1, 0x48, 0x43, 0xaf, 0x4e, 0xdb,
	0x7e, 0x9d, 0xf2, 0x36, 0xe5, 0x6a, 0xd9, 0xe2, 0x51, 0xd3, 0x17, 0xdd, 0x04, 0x71, 0x6f, 0x97,
	0x62, 0x12, 0xa8, 0x74, 0xe5, 0x88, 0x19, 0xd2, 0x4c, 0x50, 0xf9, 0x47, 0x01, 0x14, 0xaa, 0x3c,
	0x36, 0x52, 0x70, 0xed, 0xb2, 0x2b, 0x1e, 0xe7, 0xfb, 0xf0, 0xea, 0xac, 0xac, 0xa7, 0x7f, 0x83,
	0xce, 0xe8, 0x0d, 0x0a, 0x56, 0x67, 0x3f, 0x94, 0x87, 0x73, 0xcb, 0xcc, 0x60, 0xad, 0xf2, 0x9f,
	0x63, 0xc7, 0x84, 0x1f, 0x75, 0xb0, 0x96, 0x37, 0xf7, 0xf9, 0x57, 0xc8, 0xc9, 0xb2, 0x9e, 0xff,
	0x4b, 0xd6, 0x74, 0x03, 0x66, 0xdd, 0x30, 0xbf, 0x01, 0x33, 0xd8, 0xdf, 0x34, 0xe0, 0x97, 0x03,
	0xaf, 0xbc, 0x3e, 0xeb, 0xdb, 0xfa, 0x79, 0xdf, 0xd6, 0xbf, 0xf5, 0x6d, 0xfd, 0xd3, 0xc0, 0xd6,
	0xce, 0x07, 0xb6, 0xf6, 0x65, 0x60, 0x6b, 0x6f, 0xcb, 0x53, 0xbe, 0xaa, 0xbd, 0x08, 0xf6, 0x6b,
	0x07, 0xc1, 0xbe, 0x9f, 0x11, 0x6c, 0xd5, 0x1b, 0x10, 0x13, 0xff, 0x64, 0xfc, 0xfc, 0x49, 0x9f,
	0x85, 0x45, 0xf9, 0xe4, 0x3d, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x52, 0x43, 0x70, 0x4f, 0x8d,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ClaimAllocation defines a method to claim allocation
	ClaimAllocation(ctx context.Context, in *MsgClaimAllocation, opts ...grpc.CallOption) (*MsgClaimAllocationResponse, error)
	// SetAllocation defines a method to set allocation
	SetAllocation(ctx context.Context, in *MsgSetAllocation, opts ...grpc.CallOption) (*MsgSetAllocationResponse, error)
	// TransferModuleOwnership defines a method to transfer module ownership to other address
	TransferModuleOwnership(ctx context.Context, in *MsgTransferModuleOwnership, opts ...grpc.CallOption) (*MsgTransferModuleOwnershipResponse, error)
	// DepositTokens defines a method to deposit tokens to the module
	DepositTokens(ctx context.Context, in *MsgDepositTokens, opts ...grpc.CallOption) (*MsgDepositTokensResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimAllocation(ctx context.Context, in *MsgClaimAllocation, opts ...grpc.CallOption) (*MsgClaimAllocationResponse, error) {
	out := new(MsgClaimAllocationResponse)
	err := c.cc.Invoke(ctx, "/teritori.airdrop.v1beta1.Msg/ClaimAllocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetAllocation(ctx context.Context, in *MsgSetAllocation, opts ...grpc.CallOption) (*MsgSetAllocationResponse, error) {
	out := new(MsgSetAllocationResponse)
	err := c.cc.Invoke(ctx, "/teritori.airdrop.v1beta1.Msg/SetAllocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferModuleOwnership(ctx context.Context, in *MsgTransferModuleOwnership, opts ...grpc.CallOption) (*MsgTransferModuleOwnershipResponse, error) {
	out := new(MsgTransferModuleOwnershipResponse)
	err := c.cc.Invoke(ctx, "/teritori.airdrop.v1beta1.Msg/TransferModuleOwnership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DepositTokens(ctx context.Context, in *MsgDepositTokens, opts ...grpc.CallOption) (*MsgDepositTokensResponse, error) {
	out := new(MsgDepositTokensResponse)
	err := c.cc.Invoke(ctx, "/teritori.airdrop.v1beta1.Msg/DepositTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ClaimAllocation defines a method to claim allocation
	ClaimAllocation(context.Context, *MsgClaimAllocation) (*MsgClaimAllocationResponse, error)
	// SetAllocation defines a method to set allocation
	SetAllocation(context.Context, *MsgSetAllocation) (*MsgSetAllocationResponse, error)
	// TransferModuleOwnership defines a method to transfer module ownership to other address
	TransferModuleOwnership(context.Context, *MsgTransferModuleOwnership) (*MsgTransferModuleOwnershipResponse, error)
	// DepositTokens defines a method to deposit tokens to the module
	DepositTokens(context.Context, *MsgDepositTokens) (*MsgDepositTokensResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimAllocation(ctx context.Context, req *MsgClaimAllocation) (*MsgClaimAllocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimAllocation not implemented")
}
func (*UnimplementedMsgServer) SetAllocation(ctx context.Context, req *MsgSetAllocation) (*MsgSetAllocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAllocation not implemented")
}
func (*UnimplementedMsgServer) TransferModuleOwnership(ctx context.Context, req *MsgTransferModuleOwnership) (*MsgTransferModuleOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferModuleOwnership not implemented")
}
func (*UnimplementedMsgServer) DepositTokens(ctx context.Context, req *MsgDepositTokens) (*MsgDepositTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositTokens not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimAllocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teritori.airdrop.v1beta1.Msg/ClaimAllocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimAllocation(ctx, req.(*MsgClaimAllocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetAllocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teritori.airdrop.v1beta1.Msg/SetAllocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetAllocation(ctx, req.(*MsgSetAllocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferModuleOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferModuleOwnership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferModuleOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teritori.airdrop.v1beta1.Msg/TransferModuleOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferModuleOwnership(ctx, req.(*MsgTransferModuleOwnership))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DepositTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DepositTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teritori.airdrop.v1beta1.Msg/DepositTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DepositTokens(ctx, req.(*MsgDepositTokens))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "teritori.airdrop.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimAllocation",
			Handler:    _Msg_ClaimAllocation_Handler,
		},
		{
			MethodName: "SetAllocation",
			Handler:    _Msg_SetAllocation_Handler,
		},
		{
			MethodName: "TransferModuleOwnership",
			Handler:    _Msg_TransferModuleOwnership_Handler,
		},
		{
			MethodName: "DepositTokens",
			Handler:    _Msg_DepositTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teritori/airdrop/v1beta1/tx.proto",
}

func (m *MsgSetAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Allocation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetAllocationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetAllocationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetAllocationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimAllocationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimAllocationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimAllocationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSignData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferModuleOwnership) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferModuleOwnership) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferModuleOwnership) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferModuleOwnershipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferModuleOwnershipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferModuleOwnershipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDepositTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Amount[iNdEx].Size()
				i -= size
				if _, err := m.Amount[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Allocation.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSetAllocationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimAllocationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSignData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferModuleOwnership) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferModuleOwnershipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDepositTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgDepositTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allocation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Allocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetAllocationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetAllocationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetAllocationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimAllocationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimAllocationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimAllocationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSignData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferModuleOwnership) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferModuleOwnership: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferModuleOwnership: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferModuleOwnershipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferModuleOwnershipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferModuleOwnershipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Coin
			m.Amount = append(m.Amount, v)
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
