// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nxtpop/nftstaking/v1beta1/nftstaking.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NftStaking struct {
	NftIdentifier string `protobuf:"bytes,1,opt,name=nft_identifier,json=nftIdentifier,proto3" json:"nft_identifier,omitempty"`
	NftMetadata   string `protobuf:"bytes,2,opt,name=nft_metadata,json=nftMetadata,proto3" json:"nft_metadata,omitempty"`
	RewardAddress string `protobuf:"bytes,3,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
	RewardWeight  uint64 `protobuf:"varint,4,opt,name=reward_weight,json=rewardWeight,proto3" json:"reward_weight,omitempty"`
}

func (m *NftStaking) Reset()         { *m = NftStaking{} }
func (m *NftStaking) String() string { return proto.CompactTextString(m) }
func (*NftStaking) ProtoMessage()    {}
func (*NftStaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1521821ead4e6a, []int{0}
}
func (m *NftStaking) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftStaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftStaking.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftStaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftStaking.Merge(m, src)
}
func (m *NftStaking) XXX_Size() int {
	return m.Size()
}
func (m *NftStaking) XXX_DiscardUnknown() {
	xxx_messageInfo_NftStaking.DiscardUnknown(m)
}

var xxx_messageInfo_NftStaking proto.InternalMessageInfo

func (m *NftStaking) GetNftIdentifier() string {
	if m != nil {
		return m.NftIdentifier
	}
	return ""
}

func (m *NftStaking) GetNftMetadata() string {
	if m != nil {
		return m.NftMetadata
	}
	return ""
}

func (m *NftStaking) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

func (m *NftStaking) GetRewardWeight() uint64 {
	if m != nil {
		return m.RewardWeight
	}
	return 0
}

func init() {
	proto.RegisterType((*NftStaking)(nil), "nxtpop.nftstaking.v1beta1.NftStaking")
}

func init() {
	proto.RegisterFile("nxtpop/nftstaking/v1beta1/nftstaking.proto", fileDescriptor_ac1521821ead4e6a)
}

var fileDescriptor_ac1521821ead4e6a = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x31, 0x4b, 0xfc, 0x30,
	0x18, 0xc7, 0xf1, 0xe6, 0xff, 0x3f, 0x04, 0xe3, 0xe9, 0xd0, 0xa9, 0x2e, 0xe1, 0x54, 0x84, 0x43,
	0xb0, 0xe1, 0x70, 0x74, 0x52, 0x27, 0x07, 0xf5, 0xb8, 0x43, 0x04, 0x97, 0xf2, 0xb4, 0x49, 0xda,
	0x20, 0x4d, 0x4a, 0xfa, 0xe8, 0x9d, 0xef, 0xc2, 0xd7, 0xe0, 0xab, 0x71, 0xbc, 0xd1, 0x51, 0xda,
	0x37, 0x22, 0xd7, 0x14, 0xe9, 0xfa, 0xc9, 0x97, 0x07, 0xf2, 0xa3, 0x67, 0x66, 0x8d, 0x95, 0xad,
	0xb8, 0x51, 0x58, 0x23, 0xbc, 0x68, 0x93, 0xf3, 0xb7, 0x59, 0x2a, 0x11, 0x66, 0x03, 0x8a, 0x2b,
	0x67, 0xd1, 0x86, 0x87, 0xbe, 0x8d, 0x07, 0x0f, 0x7d, 0x7b, 0xfc, 0x49, 0x28, 0xbd, 0x57, 0xb8,
	0xf4, 0x1c, 0x9e, 0xd2, 0x03, 0xa3, 0x30, 0xd1, 0x42, 0x1a, 0xd4, 0x4a, 0x4b, 0x17, 0x91, 0x09,
	0x99, 0xee, 0x2e, 0xf6, 0x8d, 0xc2, 0xdb, 0x3f, 0x0c, 0x8f, 0xe8, 0x78, 0x9b, 0x95, 0x12, 0x41,
	0x00, 0x42, 0xf4, 0xaf, 0x8b, 0xf6, 0x8c, 0xc2, 0xbb, 0x9e, 0xb6, 0x97, 0x9c, 0x5c, 0x81, 0x13,
	0x09, 0x08, 0xe1, 0x64, 0x5d, 0x47, 0xff, 0xfd, 0x25, 0xaf, 0x57, 0x1e, 0xc3, 0x13, 0xda, 0x43,
	0xb2, 0x92, 0x3a, 0x2f, 0x30, 0x1a, 0x4d, 0xc8, 0x74, 0xb4, 0x18, 0x7b, 0x7c, 0xea, 0xec, 0xfa,
	0xf1, 0xab, 0x61, 0x64, 0xd3, 0x30, 0xf2, 0xd3, 0x30, 0xf2, 0xd1, 0xb2, 0x60, 0xd3, 0xb2, 0xe0,
	0xbb, 0x65, 0xc1, 0xf3, 0x65, 0xae, 0xb1, 0x78, 0x4d, 0xe3, 0xcc, 0x96, 0x7c, 0xfe, 0x30, 0x5f,
	0x96, 0xe0, 0xf0, 0xc6, 0x1a, 0x74, 0x90, 0x21, 0xf7, 0xbf, 0x3e, 0xcf, 0x0a, 0xd0, 0x86, 0xaf,
	0x87, 0x4b, 0xe1, 0x7b, 0x25, 0xeb, 0x74, 0xa7, 0x5b, 0xe7, 0xe2, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x7f, 0x10, 0x25, 0x31, 0x4b, 0x01, 0x00, 0x00,
}

func (m *NftStaking) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftStaking) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftStaking) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardWeight != 0 {
		i = encodeVarintNftstaking(dAtA, i, uint64(m.RewardWeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintNftstaking(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NftMetadata) > 0 {
		i -= len(m.NftMetadata)
		copy(dAtA[i:], m.NftMetadata)
		i = encodeVarintNftstaking(dAtA, i, uint64(len(m.NftMetadata)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NftIdentifier) > 0 {
		i -= len(m.NftIdentifier)
		copy(dAtA[i:], m.NftIdentifier)
		i = encodeVarintNftstaking(dAtA, i, uint64(len(m.NftIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNftstaking(dAtA []byte, offset int, v uint64) int {
	offset -= sovNftstaking(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NftStaking) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NftIdentifier)
	if l > 0 {
		n += 1 + l + sovNftstaking(uint64(l))
	}
	l = len(m.NftMetadata)
	if l > 0 {
		n += 1 + l + sovNftstaking(uint64(l))
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovNftstaking(uint64(l))
	}
	if m.RewardWeight != 0 {
		n += 1 + sovNftstaking(uint64(m.RewardWeight))
	}
	return n
}

func sovNftstaking(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNftstaking(x uint64) (n int) {
	return sovNftstaking(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NftStaking) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNftstaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftStaking: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftStaking: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftMetadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftMetadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeight", wireType)
			}
			m.RewardWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNftstaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNftstaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNftstaking(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNftstaking
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNftstaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNftstaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNftstaking
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNftstaking
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNftstaking
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNftstaking        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNftstaking          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNftstaking = fmt.Errorf("proto: unexpected end of group")
)
